package com.tiffy.flyring;

/**
 * BuildInfo - Build metadata (auto-generated by build script)
 */
public class BuildInfo {
    public static final String VERSION = "0.3.566";
    public static final String BUILD_NUMBER = "566";
    public static final int CONFIG_VERSION = 4;
}
